server:
  port: 9090

spring:
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
        enable_lazy_load_no_trans: true
  liquibase:
    default-schema: ${POSTGRES_SCHEMA:public}
    change-log: classpath:/${POSTGRES_SCHEMA:public}/master.yml